os: linux
language: python
python:
- 3.6
- 3.7-dev

matrix:
  include:
  - name: Lint
    language: rust
    rust: nightly
    install:
    - rustup component add rustfmt
    - rustup component add clippy
    script:
    - cargo fmt --all -- --check
    - find solutions -name '*.rs' | xargs -I {} rustfmt --check {}
    - find examples -name '*.rs' | xargs -I {} rustfmt --check {}
    - cargo clippy --all-features
    - cd porus_macros
    - cargo clippy
    - cd ..
    after_success:
    cache:
      directories:
      - $HOME/.cargo
      - $TRAVIS_BUILD_DIR/target
  - os: osx
    language: generic
    python: 3.6
    before_install:
    - curl -Lo python.pkg https://www.python.org/ftp/python/3.6.6/python-3.6.6-macosx10.6.pkg
    - sudo installer -pkg python.pkg -target /
    - /Applications/Python\ 3.6/Install\ Certificates.command
  allow_failures:
  - python: "3.7-dev"
env:
  global:
  - PATH=${PATH}:${HOME}/.cargo/bin
  matrix:
  - TRAVIS_RUST_VERSION=nightly
install:
- cd /tmp
- curl -sSf https://sh.rustup.rs/ | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rustup target add x86_64-unknown-linux-gnu; fi
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install cargo-update || echo "cargo-update already installed"
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install --git git://github.com/bhuztez/cov cargo-cov || echo "cargo-cov already installed"
- CARGO_TARGET_DIR="${HOME}/.cargo/target" cargo install-update -ag
- cd "$TRAVIS_BUILD_DIR"
- pip3 install -r requirements.txt
script:
- cargo test --verbose
- cargo test --release --verbose
- VERBOSE=1 python3 c.py test solutions
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then VERBOSE=1 python3 c.py test --mode release solutions; fi
- VERBOSE=1 python3 c.py clean
- find solutions -name '*.rs' | xargs -I {} python3 c.py preview {}
- find examples -name '*.rs' | xargs -I {} python3 c.py preview {}
- VERBOSE=1 python3 c.py clean
- VERBOSE=1 python3 c.py clean examples
after_success:
- cargo cov clean
- VERBOSE=1 python3 c.py test --mode coverage solutions
- cargo cov test -v
- cargo cov report --coveralls
cache:
  pip: true
  directories:
  - $HOME/.cargo
  - $HOME/.cache/wronganswer/data
  - $TRAVIS_BUILD_DIR/target
